/* Main.c file generated by New Project wizard
 *
 * Created:   seg jun 2 2025
 * Processor: 80C51
 * Compiler:  SDCC for 8051
 */

#include <8051.h>

#define TIMES_INTERRUPT 40
#define TIMER0_COUNTER 65535 - 46080 + 8

unsigned char milisegundos;

//__bit__at (0x20) flagPassou1Seg;

void setup();
void configTimers();

void main(void)
{
    setup();
}

void setup()
{
    SP = 128 - 25; // Move stack pointer to end of RAM.
    configTimers();
}
void configTimers()
{
    IE = 0b10000010;
    TL0 = TIMER0_COUNTER & 0x00FF;
    TH0 = TIMER0_COUNTER & 0xFF00;
    TMOD = 0b01010001;
    TL1 = 0;
    TH1 = 0;
    milisegundos = TIMES_INTERRUPT;
}